### ISSUE TITLE
Can local processing be done for all raw data?

### ISSUE THREAD

**Issue by rsignell-usgs** [friedrichknuth/ooi_local_processing#6]
Could the same approach used in the example [here](https://github.com/friedrichknuth/ooi_local_processing/blob/master/parse_process.ipynb) be applied for all data found on [OOI raw data server](https://rawdata.oceanobservatories.org/files)?

**Comment by friedrichknuth** [comment]
Yes - the same can be applied for any data product that is generated by OOINet from raw data on the archive. Note that not all raw data found on the raw data archive is processed via OOINet data product parsers and algorithms. Exceptions include the hydrophone data, seismic data, camera data and a hand full of other data products that are not currently being processed by OOINet. http://oceanobservatories.org/core-instrument-analytical-results/

**Comment by rsignell-usgs** [comment]
Thanks!
